version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    depends_on:
      - discovery

  rabbitmq:
    image:  "rabbitmq:3"

  discovery:
    image: 'consul:1.8'
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  redis:
    image: "redis:latest"

  postgres-auth:
    image: 'postgres:10'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-auth

