spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: Port
          uri: lb://port-service
          predicates:
            - Path=/api/port*/**
        - id: Boat
          uri: lb://boat-service
          predicates:
            - Path=/api/boat*/**
        - id: trip
          uri: lb://trip-service
          predicates:
            - Path=/api/trips*/**

        - id: frontend
          uri: http://frontend:3000
          predicates:
            - Path=/**
